### ISSUE TITLE
Wrong Content-type header

### ISSUE THREAD

**Issue by alexdevmotion** [DaAwesomeP/php-offline-fonts#4]
It did not work for me until i added this line inside GoogleFontsCSS:

``` php
header('Content-type:text/css');
```

It treated the generated file as text/html.
This is an easy fix which can be included.

**Comment by DaAwesomeP** [comment]
I see. Please note that this script will eventually fail. It will download all of the CSS files until it fails. It is also very slow. If one user in one obscure browser accesses the site (and never again), then it will save the CSS for it. However, the cache then builds and builds. The never accessed CSS files will still be there taking up space. I would recommend that you simply download the font files manually from the creator's site (or run the script for a while and then keep the font files and not the CSS files). Most browsers handle font hinting fine now. You still have to get around Google not having cache headers though.

**Comment by DaAwesomeP** [comment]
I added your fix. It would be better to set the content header via Apache or Nginx. If you set in in PHP, then Apache and Nginx will at first tell the browser HTML, but the PHP will "change" it. This is a little of a performance drag and is also simply bad practice (changing a header after it has already been sent once).
